from setuptools import setup, find_packages

setup(
    name='django-password-strength',
    version='1.4.1',
    url='https://github.com/alessandrohc/django-password-strength',
    author='Alessandro Hecht',
    author_email='alessandrohc@gmail.com',
    maintainer='Alessandro Hecht',
    maintainer_email='alessandrohc@gmail.com',
    description='This package contains an extension of the Django password widget including a password strength meter and crack time powered by zxcvbn.',
    keywords='password meter zxcvbn strength security django',
    license='BSD',
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        'password-strength @ https://github.com/alessandrohc/py-password-strength/archive/refs/tags/v0.0.5.zip#egg=password-strength-0.0.5',
    ],
    zip_safe=False,
    python_requires='>=3.8',
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Environment :: Web Environment',
        'Framework :: Django',
        'Framework :: Django :: 3.2',
        'Framework :: Django :: 4.2',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: BSD License',
        'Operating System :: OS Independent',
        'Natural Language :: English',
        'Natural Language :: Portuguese (Brazilian)',
        'Natural Language :: Russian',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'Programming Language :: Python :: 3.12',
        'Topic :: Internet :: WWW/HTTP',
    ],
)
